;;; Automatically generated by ‘recentf’ on Tue Oct 25 00:09:56 2022.

(setq recentf-list
      '(
        "/home/cleff/orgs/org-roam.org"
        "/home/cleff/.emacs.d/init.el"
        "/home/cleff/.config/emacs/init.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
